#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jboss-parent
Version  : 21
Release  : 4
URL      : https://github.com/jboss/jboss-parent-pom/archive/jboss-parent-21.tar.gz
Source0  : https://github.com/jboss/jboss-parent-pom/archive/jboss-parent-21.tar.gz
Source1  : https://repo1.maven.org/maven2/org/jboss/jboss-parent/16/jboss-parent-16.pom
Source2  : https://repo1.maven.org/maven2/org/jboss/jboss-parent/21/jboss-parent-21.pom
Source3  : https://repo1.maven.org/maven2/org/jboss/jboss-parent/6/jboss-parent-6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Public-Domain
Requires: mvn-jboss-parent-data = %{version}-%{release}

%description
JBoss Parent POM
=================
The parent Maven POM for JBoss community projects.

%package data
Summary: data components for the mvn-jboss-parent package.
Group: Data

%description data
data components for the mvn-jboss-parent package.


%prep
%setup -q -n jboss-parent-pom-jboss-parent-21

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/jboss-parent/16
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jboss/jboss-parent/16/jboss-parent-16.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/jboss-parent/21
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/jboss/jboss-parent/21/jboss-parent-21.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/jboss-parent/6
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/jboss/jboss-parent/6/jboss-parent-6.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jboss/jboss-parent/16/jboss-parent-16.pom
/usr/share/java/.m2/repository/org/jboss/jboss-parent/21/jboss-parent-21.pom
/usr/share/java/.m2/repository/org/jboss/jboss-parent/6/jboss-parent-6.pom
