#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jboss-parent
Version  : 21
Release  : 1
URL      : https://github.com/jboss/jboss-parent-pom/archive/jboss-parent-21.tar.gz
Source0  : https://github.com/jboss/jboss-parent-pom/archive/jboss-parent-21.tar.gz
Source1  : https://repo1.maven.org/maven2/org/jboss/jboss-parent/21/jboss-parent-21.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Public-Domain
Requires: mvn-jboss-parent-data = %{version}-%{release}

%description
JBoss Parent POM
=================
The parent Maven POM for JBoss community projects.

%package data
Summary: data components for the mvn-jboss-parent package.
Group: Data

%description data
data components for the mvn-jboss-parent package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jboss/jboss-parent/21
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jboss/jboss-parent/21/jboss-parent-21.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jboss/jboss-parent/21/jboss-parent-21.pom
